# Generated by Django 3.0.2 on 2020-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('signing_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('last_login_date', models.DateField(auto_now_add=True, verbose_name='تاریخ آخرین ورود')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stuff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=70, verbose_name='نام خانوادگی')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
