# Generated by Django 3.0.2 on 2020-01-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
